baseURL = 'https://www.neonsports.cn/'
languageCode = 'zh-CN'
title = '上海聚余服饰有限公司'
theme = 'neonsite'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
tableOfContents =true

[languages]
  [languages.zh]
    contentDir = 'content/zh'
    disabled = false
    languageCode = 'zh-CN'
    languageDirection = 'ltr'
    languageName = '中文'
    title = '上海聚余服饰有限公司'
    weight = 2
    [languages.zh.menus]
      [[languages.zh.menus.main]]
        name = '网站首页'
        pageRef = '/'
        weight = 10
        pre = 'tiny'
      [[languages.zh.menus.main]]
        name = '公司简介'
        pageRef = '/company'
        weight = 20
        pre = 'medium'
      [[languages.zh.menus.main]]
         name = '产品中心'
         pageRef = '/products'
         weight = 30
         pre = 'medium'
      [[languages.zh.menus.main]]
         name = '高端定制'
         pageRef = '/products/custom'
         weight = 40
         pre = 'tiny'
      [[languages.zh.menus.main]]
        name = '诚招代理'
        pageRef = '/agent'
        weight = 50
        pre = 'small'
      [[languages.zh.menus.main]]
        name = '联系我们'
        pageRef = '/contact'
        weight = 60
        pre = 'tiny'
      [[languages.zh.menus.main]]
        name = '常见问题'
        pageRef = '/faq'
        weight = 70
        pre = 'medium'
      [[languages.zh.menus.tiny]]
        name = '网站首页'
        pageRef = '/'
        weight = 10
      [[languages.zh.menus.tiny]]
        name = '高端定制'
        pageRef = '/products/custom'
        weight = 20
      [[languages.zh.menus.tiny]]
        name = '联系我们'
        pageRef = '/contact'
        weight = 30
    [languages.zh.params]
      productscatalories = '产品类别'
      mission = '专注于热升华转印运动服装的领先公司'
      productstip = '欢迎来电咨询我们的产品'
      contactus = '联系我们'
      productdetail = "商品详情"
      contactusurl = '/contact'
      onlinemessagetitle = '在线留言'
      onlinemessagetip = '如果您有任何疑问、意见或建议,或需进一步了解产品详细信息,请填写以下表单,以获得及时的帮助与支持'
      companyname = '上海聚余服饰有限公司'
      copyrightmsg = '版权所有'
      productdetailsizevalueerror = "每个样品订单最多可以订购5件"
      shippingaddress = "货物收货地址"
      noshippingaddress = "请输入货物收货地址"
      yourname = "您的姓名"
      noyourname = "请输入您的姓名"
      organizationname = '组织名称'
      mobile = '手机或电话号码'
      email = "电子邮箱地址"
      wechat = '微信号码'
      skype = 'Skype'
      whatsApp = 'WhatsApp'
      ordernote = '订单留言'
      verifycodemsg = "请输入图片上的验证码"
      nocontactinformation = "请输入至少一个联系方式"
      verifycodeurl = "https://www.sysadm.cn/vcode.php"
      sendmailurl = 'https://www.sysadm.cn/sendemail.php'
      sendButtontitle = '发送'
      closeButtontitle = '关闭'
      ordersamplebuttontitle = '订购样品'
      orderstartrequestbuttontitle = '订购'
      prices = '价格'
      variations = '可选'
      totaloptions = '所有选项'
      size = '尺寸'
      samples = '样品'
      jsUnknowError = "未知错误"
      jsServerError = "服务器处理错误"
      jsTimeOut = "网络超时"
      jsParseError = "解析错误"
      jsSuccessful = "数据发送成功"
      jsInvalidVcode = "验证码错误"
      [languages.zh.params.products]
        [languages.zh.params.products.0]
          title = '蓝球服'
          pic = '/images/products/basketball-1.png'
          url = 'basketball'
          prefontname = 'fa-pencil'
        [languages.zh.params.products.1]
          title = '骑行服'
          pic = '/images/cycling.png'
          url = 'cycling'
          prefontname = 'fa-plane'
        [languages.zh.params.products.2]
          title = '足球服'
          pic = '/images/football.png'
          url = 'football'
          prefontname = 'fa-chain'
        [languages.zh.params.products.3]
          title = '冰球服'
          pic = '/images/products/ice_hockey_1.png'
          url = 'ice_hockey'
          prefontname = 'fa-arrows'
        [languages.zh.params.products.4]
          title = '曲棍球服'
          pic = '/images/products/lacrosse_1.png'
          url = 'lacrosse'
          prefontname = 'fa-dashboard'
        [languages.zh.params.products.5]
          title = '棒球服'
          pic = '/images/products/baseball_1.png'
          url = 'baseball'
          prefontname = 'fa-fighter-jet'
        [languages.zh.params.products.6]
          title = '抱枕'
          pic = '/images/products/pillow_1.png'
          url = 'pillow'
          prefontname = 'fa-life-ring'
        [languages.zh.params.products.7]
          title = 'Polo衫'
          pic = '/images/products/polo_shirt_1.png'
          url = 'polo_shirt'
          prefontname = 'fa-trophy'
        [languages.zh.params.products.8]
          title = '橄榄球服'
          pic = '/images/products/rugby_1.png'
          url = 'rugby'
          prefontname = 'fa-star-half'
        [languages.zh.params.products.9]
          title = '摔跤服'
          pic = '/images/products/wrestling_1.png'
          url = 'wrestling'
          prefontname = 'fa-ticket'
      [languages.zh.params.contacts]
        [languages.zh.params.contacts.0]
          fontname = 'fas fa-phone'
          content = '15391822710'
          title = '咨询电话'
          url = ''
        [languages.zh.params.contacts.1]
          fontname = 'fas fa-envelope'
          content = 'neonsports@163.com'
          title = '企业邮箱'
          url = 'mailto: neonsports@163.com'
        [languages.zh.params.contacts.2]
          fontname = 'fab fa-weixin'
          content = '1539182270'
          title = '微信客服'
          url = ''
        [languages.zh.params.contacts.3]
          fontname = 'fab fa-qq'
          content = '150694131'
          title = 'QQ客服'
          url = ''
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Shanghai Neon SportsWear'
    weight = 1
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'Home'
        pageRef = '/'
        weight = 10
        pre = 'tiny'
      [[languages.en.menus.main]]
        name = 'Company'
        pageRef = '/company'
        weight = 20
        pre = 'medium'
      [[languages.en.menus.main]]
        name = 'Products'
        pageRef = '/products'
        weight = 30
        pre = 'medium'
      [[languages.en.menus.main]]
        name = 'Custom'
        pageRef = '/products/custom'
        weight = 40
        pre = 'tiny'
      [[languages.en.menus.main]]
        name = 'Recruit Agents'
        pageRef = '/agent'
        weight = 50
        pre = 'small'
      [[languages.en.menus.main]]
        name = 'Contact'
        pageRef = '/contact'
        weight = 60
        pre = 'tiny'
      [[languages.en.menus.main]]
        name = 'FAQ'
        pageRef = '/faq'
        weight = 70
        pre = 'medium'
      [[languages.en.menus.tiny]]
        name = 'Home'
        pageRef = '/'
        weight = 10
      [[languages.en.menus.tiny]]
        name = 'Custom'
        pageRef = '/products/custom'
        weight = 20
      [[languages.en.menus.tiny]]
        name = 'Contact'
        pageRef = '/contact'
        weight = 30
    [languages.en.params]
      productscatalories = 'Product Categories'
      mission = 'A leading company dedicated to advancing sublimation printing sportswear'
      productstip = 'Welcome to inquire about our products'
      contactus = 'Contact Us'
      productdetail = "Details"
      contactusurl = '/contact'
      onlinemessagetitle = 'Online Message'
      onlinemessagetip = 'If you have any questions, comments or suggestions, or need further information about the product, please fill out the following form'
      companyname = 'Shanghai Neon SportsWear Co;Ltd'
      copyrightmsg = 'All rights reserved'
      productdetailsizevalueerror = "Maximum order quantity 5 piece"
      shippingaddress = "Shipping Address"
      noshippingaddress = "Please input shipping address"
      yourname = "Your Name"
      noyourname = "Please input your name"
      organizationname = 'Organization Name'
      mobile = 'MP/Tel'
      email = 'Email Address'
      wechat = 'Wechat'
      skype = 'Skype'
      whatsApp = 'WhatsApp'
      ordernote = 'Order Note'
      verifycodemsg = "Please input the verify code on the picture"
      verifycodeurl = "https://www.sysadm.cn/vcode.php"
      sendmailurl = 'https://www.sysadm.cn/sendemail.php'
      sendButtontitle = 'Sent'
      closeButtontitle = 'Close'
      ordersamplebuttontitle = 'Order Sample'
      orderstartrequestbuttontitle = 'Order Request'
      nocontactinformation = "Please enter at least one contact information"
      prices = 'Prices'
      variations = 'Variations'
      totaloptions = 'Total Options'
      maximumorderquantity = 'Maximum order quantity'
      piece = 'piece'
      jsUnknowError = "Unknow Error"
      jsServerError = "Server Error"
      jsTimeOut = "TimeOut"
      jsParseError = "Parsing Error"
      jsSuccessful = "data has be sent"
      jsInvalidVcode = "Verify code Incorret"
      [languages.en.params.products]
        [languages.en.params.products.0]
          title = 'Basketball'
          pic = '/images/products/basketball-1.png'
          url = 'basketball'
          prefontname = 'fa-pencil'
        [languages.en.params.products.1]
          title = 'Cycling'
          pic = '/images/cycling.png'
          url = 'cycling'
          prefontname = 'fa-plane'
        [languages.en.params.products.2]
          title = 'Football'
          pic = '/images/football.png'
          url = 'football'
          prefontname = 'fa-chain'
        [languages.en.params.products.3]
          title = 'Ice Hockey'
          pic = '/images/products/ice_hockey_1.png'
          url = 'ice_hockey'
          prefontname = 'fa-arrows'
        [languages.en.params.products.4]
          title = 'Lacrosse'
          pic = '/images/products/lacrosse_1.png'
          url = 'lacrosse'
          prefontname = 'fa-dashboard'
        [languages.en.params.products.5]
          title = 'Baseball'
          pic = '/images/products/baseball_1.png'
          url = 'baseball'
          prefontname = 'fa-fighter-jet'
        [languages.en.params.products.6]
          title = 'Pillow'
          pic = '/images/products/pillow_1.png'
          url = 'pillow'
          prefontname = 'fa-life-ring'
        [languages.en.params.products.7]
          title = 'Polo Shirt'
          pic = '/images/products/polo_shirt_1.png'
          url = 'polo_shirt'
          prefontname = 'fa-trophy'
        [languages.en.params.products.8]
          title = 'Rugby'
          pic = '/images/products/rugby_1.png'
          url = 'rugby'
          prefontname = 'fa-star-half'
        [languages.en.params.products.9]
          title = 'Wrestling'
          pic = '/images/products/wrestling_1.png'
          url = 'wrestling'
          prefontname = 'fa-ticket'
      [languages.en.params.contacts]
        [languages.en.params.contacts.0]
          fontname = 'fas fa-phone'
          content = '(+86) 15391822710'
          title = 'Mobile Phone'
          url = ''
        [languages.en.params.contacts.1]
          fontname = 'fas fa-envelope'
          content = 'neonsports@163.com'
          title = 'Email'
          url = 'mailto: neonsports@163.com'
        [languages.en.params.contacts.2]
          fontname = 'fab fa-weixin'
          content = '15391822710'
          title = 'Wechat'
          url = ''
        [languages.en.params.contacts.3]
          fontname = 'fab fa-skype'
          content = 'neonsports@163.com'
          title = 'Skype'
          url = 'https://join.skype.com/invite/rdX35sOidYO3'
        [languages.en.params.contacts.4]
          fontname = 'fab fa-whatsapp'
          content = '+8615391822710'
          title = 'WhatsApp'
          url = 'https://api.whatsapp.com/send/?phone=8615391822710'